dist: bionic

language: c

notifications:
 - email: true

before_script:
 # Download the kernel
 - sudo apt-get install libelf-dev wget tar gzip python
 - wget https://mirrors.edge.kernel.org/pub/linux/kernel/v4.x/linux-4.1.36.tar.gz
 - tar xf linux-4.1.36.tar.gz
 - mv linux-4.1.36 linux-stable
 - ./.travis_get_mainline_kernel
 # Prerequisite for xfstests testing
 - sudo apt-get install cifs-utils
 - sudo apt-get install linux-headers-$(uname -r)
 - sudo apt-get install autoconf libtool pkg-config libnl-3-dev libnl-genl-3-dev
 - sudo apt-get install xfslibs-dev uuid-dev libtool-bin xfsprogs libgdbm-dev gawk fio attr libattr1-dev libacl1-dev libaio-dev
 - git clone https://github.com/cifsd-team/cifsd-tools
 - git clone https://github.com/cifsd-team/cifsd-test-result
 - export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
 - export PATH=/usr/local/lib:$PATH
 - sudo useradd fsgqa
 - sudo useradd 123456-fsgqa
 # Prerequisite for smbtorture testing
 - sudo apt-get install liblmdb-dev libgnutls28-dev libgpgme-dev libjansson-dev libarchive-dev libacl1-
dev

script:
 # Copy cifsd source to kernel
 - mv linux-stable ../
 - mv linux ../
 - mkdir ../linux-stable/fs/cifsd
 - cp -ar * ../linux-stable/fs/cifsd/
 - mkdir ../linux/fs/cifsd
 - cp -ar * ../linux/fs/cifsd/

 # Compile with 4.1 kernel
 - cd ../linux-stable
 - yes "" | make oldconfig > /dev/null
 - echo 'obj-$(CONFIG_CIFS_SERVER) += cifsd/' >> fs/Makefile
 - echo 'source "fs/cifsd/Kconfig"' >> fs/Kconfig
 - echo 'CONFIG_CIFS_SERVER=m' >> .config
 - echo 'CONFIG_CIFS_INSECURE_SERVER=y' >> .config
 - gcc -v
 - make fs/cifsd/cifsd.ko

 # Compile with latest Tovalds' kernel
 - cd ../linux
 - yes "" | make oldconfig > /dev/null
 - echo 'obj-$(CONFIG_CIFS_SERVER) += cifsd/' >> fs/Makefile
 - echo 'source "fs/cifsd/Kconfig"' >> fs/Kconfig
 - echo 'CONFIG_CIFS_SERVER=m' >> .config
 - echo 'CONFIG_CIFS_INSECURE_SERVER=y' >> .config
 - gcc -v
 - make fs/cifsd/cifsd.ko

 # Compile secure server build (no smb1.0 & smb2.0) with 4.1 kernel
 - cd ../linux-stable
 - yes "" | make oldconfig > /dev/null
 - echo 'obj-$(CONFIG_CIFS_SERVER) += cifsd/' >> fs/Makefile
 - echo 'source "fs/cifsd/Kconfig"' >> fs/Kconfig
 - echo 'CONFIG_CIFS_SERVER=m' >> .config
 - echo '# CONFIG_CIFS_INSECURE_SERVER is not set' >> .config
 - gcc -v
 - make fs/cifsd/cifsd.ko

 # Compile secure server build (no smb1.0 & smb2.0) with latest Tovalds' kernel
 - cd ../linux
 - yes "" | make oldconfig > /dev/null
 - echo 'obj-$(CONFIG_CIFS_SERVER) += cifsd/' >> fs/Makefile
 - echo 'source "fs/cifsd/Kconfig"' >> fs/Kconfig
 - echo 'CONFIG_CIFS_SERVER=m' >> .config
 - echo '# CONFIG_CIFS_INSECURE_SERVER is not set' >> .config
 - gcc -v
 - make fs/cifsd/cifsd.ko

 # Run xfstests testsuite
 - cd ../cifsd
 - make > /dev/null
 - sudo make install > /dev/null
 - sudo modprobe cifsd
 - sudo modprobe cifs
 - cd cifsd-tools
 - ./autogen.sh > /dev/null
 - ./configure > /dev/null
 - make > /dev/null
 - sudo make install > /dev/null
 - cd ..
 - sudo mkdir -p /etc/cifs/
 - sudo mkdir -p /mnt/1
 - sudo mkdir -p /mnt/2
 - sudo mkdir -p /mnt/test1
 - sudo mkdir -p /mnt/test2
 - cifsadmin -i ./cifspwd.db -a testuser -p 1234
 - cp cifsd-test-result/testsuites/smb.conf .
 - cifsd -n --c=./smb.conf --u=./cifspwd.db&
 - ps -ax | grep cifsd
 - cd cifsd-test-result/testsuites/
 - tar xzvf xfstests-cifsd.tgz > /dev/null
 - cd xfstests-cifsd
 - ./configure > /dev/null
 - make > /dev/null
 - sudo ./check cifs/001
 - sudo ./check generic/001
 - sudo ./check generic/002
 - sudo ./check generic/005
 - sudo ./check generic/006
 - sudo ./check generic/007
 - sudo ./check generic/011
 - sudo ./check generic/013
 - sudo ./check generic/014
 - sudo ./check generic/023
 - sudo ./check generic/024
 - sudo ./check generic/028
 - sudo ./check generic/029
 - sudo ./check generic/030
 - sudo ./check generic/036
 - sudo ./check generic/037
 - sudo ./check generic/069
# - travis_wait sudo ./check generic/070 (timeover > 10m)
 - sudo ./check generic/074
 - sudo ./check generic/075
 - sudo ./check generic/080
# - sudo ./check generic/084 #fail, It may be cifs client issue on 4.15 kernel
 - sudo ./check generic/091
 - sudo ./check generic/095
 - sudo ./check generic/098
 - sudo ./check generic/100
 - sudo ./check generic/109
 - sudo ./check generic/112
 - sudo ./check generic/113
# - time_wait sudo ./check generic/117 (timeover > 10m)
 - sudo ./check generic/124
 - sudo ./check generic/125
# - travis_wait sudo ./check generic/127 (timeover > 10m)
 - sudo ./check generic/129
 - sudo ./check generic/130
 - sudo ./check generic/133
 - sudo ./check generic/135
 - sudo ./check generic/141
 - sudo ./check generic/169
 - sudo ./check generic/198
 - sudo ./check generic/207
 - sudo ./check generic/210
 - sudo ./check generic/211
 - sudo ./check generic/212
 - sudo ./check generic/215
 - sudo ./check generic/221
 - sudo ./check generic/239
 - sudo ./check generic/245
 - sudo ./check generic/246
 - sudo ./check generic/247
 - sudo ./check generic/248
 - sudo ./check generic/249
 - sudo ./check generic/257
# - sudo ./check generic/263 #fail, It may be cifsd issue
# - sudo ./check generic/285 #fail, It may be cifs client issue on 4.15 kernel
 - sudo ./check generic/286
 - sudo ./check generic/308
 - sudo ./check generic/309
 - sudo ./check generic/315
# - sudo ./check generic/323 #fail, It may be cifs client issue on 4.15 kernel
 - sudo ./check generic/337
 - sudo ./check generic/340
 - sudo ./check generic/345
 - sudo ./check generic/354
 - sudo ./check generic/360
 - sudo ./check generic/393
 - sudo ./check generic/394
 - sudo ./check generic/406
 - sudo ./check generic/412
 - sudo ./check generic/436
 - sudo ./check generic/437
# - travis_wait sudo ./check generic/438 (timeover > 10m)
 - sudo ./check generic/445
 - sudo ./check generic/448
 - sudo ./check generic/451
 - sudo ./check generic/460
 - sudo ./check generic/464
 - sudo ./check generic/465
 - sudo ./check generic/469
# - time_wait sudo ./check generic/476 (timeover > 10m)
 - sudo ./check generic/490
# - sudo ./check generic/504 #fail, It may be cifs client issue on 4.15 kernel
 - cd ..
 - tar xzvf samba-cifsd.tgz > /dev/null
 - cd samba-cifsd/
 - ./configure > /dev/null
 - make -j > /dev/null
 - sudo make install > /dev/null
 # smb2 connect test
 - ./bin/smbtorture //127.0.0.1/cifsd-test1/ -Utestuser%1234 smb2.connect
 - sudo rm -rf /mnt/test1/*
